### ISSUE TITLE
Same test can be run against all

### ISSUE THREAD

**Issue by febael** [maboueita/algorithms#2]
https://github.com/maboueita/algorithms/blob/799a71b638db62ac10461c50a6b21a6e728cfdaa/src/sort/InsertionSort.kt#L27

Tip : One test run on all implementations of a common interface

**Comment by maboueita** [comment]
Can you elaborate what you mean by a common interface?

**Comment by maboueita** [comment]
👍a generic test will be created for all the sorting problems
